title: "Hope Johnson — Data Science"
description: "Student and Aspiring Data Scientist demonstrating Python, SQL, and R skills through projects focused on analytics and predictive modeling"
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Hope Johnson"
github_username: "mhopejohnd"
exclude:
  - "README.md"

